# Generated by Django 3.0.6 on 2020-06-04 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministrador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Detallepedido',
            fields=[
                ('idedetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detallepedido',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Estadofactura',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estadofactura',
            },
        ),
        migrations.CreateModel(
            name='Estadohabitacion',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estadohabitacion',
            },
        ),
        migrations.CreateModel(
            name='Estadopedido',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'estadopedido',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipocama', models.CharField(max_length=70)),
                ('accesorios', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('administrador', models.ForeignKey(db_column='administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Administrador')),
                ('estadohabitacion', models.ForeignKey(db_column='estadohabitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Estadohabitacion')),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tipoproducto',
            },
        ),
        migrations.CreateModel(
            name='Tiposervicio',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tiposervicio',
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'tipousuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=70)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=200)),
                ('tipousuario', models.ForeignKey(db_column='tipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Serviciocomedor',
            fields=[
                ('idservicio', models.AutoField(primary_key=True, serialize=False)),
                ('plato', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('administrador', models.ForeignKey(db_column='administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Administrador')),
                ('tiposervicio', models.ForeignKey(db_column='tiposervicio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tiposervicio')),
            ],
            options={
                'db_table': 'serviciocomedor',
            },
        ),
        migrations.CreateModel(
            name='Recepcionproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('fecharecepcion', models.DateField()),
                ('detallepedido', models.ForeignKey(db_column='detallepedido', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Detallepedido')),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Empleado')),
            ],
            options={
                'db_table': 'recepcionproducto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rubro', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
                ('stock', models.BigIntegerField()),
                ('precio', models.IntegerField()),
                ('administrador', models.ForeignKey(db_column='administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Administrador')),
                ('tipoproducto', models.ForeignKey(db_column='tipoproducto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tipoproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(max_length=255)),
                ('fechapedido', models.DateField()),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Empleado')),
                ('estadopedido', models.ForeignKey(db_column='estadopedido', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Estadopedido')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('idhuesped', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidopaterno', models.CharField(max_length=100)),
                ('apellidomaterno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=11)),
                ('fechadesde', models.DateField()),
                ('fechahasta', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
                ('habitacion', models.ForeignKey(blank=True, db_column='habitacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Habitacion')),
            ],
            options={
                'db_table': 'huesped',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('giro', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
                ('estadofactura', models.ForeignKey(db_column='estadofactura', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Estadofactura')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(db_column='pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Producto'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Proveedor'),
        ),
        migrations.CreateModel(
            name='Detallefactura',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('factura', models.ForeignKey(db_column='factura', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Factura')),
                ('huesped', models.ForeignKey(blank=True, db_column='huesped', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Huesped')),
                ('serviciocomedor', models.ForeignKey(blank=True, db_column='serviciocomedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Serviciocomedor')),
            ],
            options={
                'db_table': 'detallefactura',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Usuario'),
        ),
    ]
