# Generated by Django 3.0.6 on 2020-06-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('idsolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('huesped', models.ForeignKey(db_column='huesped', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Huesped')),
                ('serviciocomedor', models.ForeignKey(db_column='serviciocomedor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Serviciocomedor')),
            ],
        ),
    ]
