# Generated by Django 3.0.6 on 2020-06-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudcompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField()),
                ('total', models.IntegerField()),
                ('habitacion', models.ForeignKey(db_column='habitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Habitacion')),
                ('huesped', models.ForeignKey(db_column='huesped', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Huesped')),
            ],
        ),
    ]
