# Generated by Django 3.0.6 on 2020-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200603_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='fechadesde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
