# Generated by Django 3.0.6 on 2020-06-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detallereserva'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallereserva',
            table='detallereserva',
        ),
        migrations.AlterModelTable(
            name='solicitudcompra',
            table='solicitudcompra',
        ),
    ]
