# Generated by Django 3.0.6 on 2020-06-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200608_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Proveedor'),
            preserve_default=False,
        ),
    ]
