# Generated by Django 3.0.6 on 2020-06-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solicitudcompra_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empleado',
            field=models.ForeignKey(db_column='empleado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Empleado'),
            preserve_default=False,
        ),
    ]
