# Generated by Django 3.0.6 on 2020-06-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estadodetallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado',
            field=models.ForeignKey(db_column='estado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.EstadoDetallePedido'),
            preserve_default=False,
        ),
    ]
