# Generated by Django 3.0.6 on 2020-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_detallepedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionproducto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
