//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEPEDIDO
    {
        public DETALLEPEDIDO()
        {
            this.RECEPCIONPRODUCTO = new HashSet<RECEPCIONPRODUCTO>();
        }
    
        public long IDEDETALLE { get; set; }
        public long CANTIDAD { get; set; }
        public long TOTAL { get; set; }
        public long PEDIDO { get; set; }
        public long PRODUCTO { get; set; }
        public long PROVEEDOR { get; set; }
    
        public virtual PEDIDO PEDIDO1 { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
        public virtual PROVEEDOR PROVEEDOR1 { get; set; }
        public virtual ICollection<RECEPCIONPRODUCTO> RECEPCIONPRODUCTO { get; set; }
    }
}
