//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEFACTURA
    {
        public long IDDETALLE { get; set; }
        public long TOTAL { get; set; }
        public long FACTURA { get; set; }
        public Nullable<long> HUESPED { get; set; }
        public Nullable<long> SERVICIOCOMEDOR { get; set; }
    
        public virtual FACTURA FACTURA1 { get; set; }
        public virtual HUESPED HUESPED1 { get; set; }
        public virtual SERVICIOCOMEDOR SERVICIOCOMEDOR1 { get; set; }
    }
}
