//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public EMPLEADO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RECEPCIONPRODUCTO = new HashSet<RECEPCIONPRODUCTO>();
        }
    
        public long IDEMPLEADO { get; set; }
        public long USUARIO { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<RECEPCIONPRODUCTO> RECEPCIONPRODUCTO { get; set; }
    }
}
