//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        public HABITACION()
        {
            this.HUESPED = new HashSet<HUESPED>();
        }
    
        public long IDHABITACION { get; set; }
        public long NUMERO { get; set; }
        public string TIPOCAMA { get; set; }
        public string ACCESORIOS { get; set; }
        public long PRECIO { get; set; }
        public long ADMINISTRADOR { get; set; }
        public long ESTADOHABITACION { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR1 { get; set; }
        public virtual ESTADOHABITACION ESTADOHABITACION1 { get; set; }
        public virtual ICollection<HUESPED> HUESPED { get; set; }
    }
}
