//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUESPED
    {
        public HUESPED()
        {
            this.DETALLEFACTURA = new HashSet<DETALLEFACTURA>();
        }
    
        public long IDHUESPED { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECHADESDE { get; set; }
        public Nullable<System.DateTime> FECHAHASTA { get; set; }
        public long CLIENTE { get; set; }
        public Nullable<long> HABITACION { get; set; }
    
        public virtual CLIENTE CLIENTE1 { get; set; }
        public virtual ICollection<DETALLEFACTURA> DETALLEFACTURA { get; set; }
        public virtual HABITACION HABITACION1 { get; set; }
    }
}
