//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.DETALLEPEDIDO = new HashSet<DETALLEPEDIDO>();
        }
    
        public long IDPEDIDO { get; set; }
        public string OBSERVACIONES { get; set; }
        public System.DateTime FECHAPEDIDO { get; set; }
        public long EMPLEADO { get; set; }
        public long ESTADOPEDIDO { get; set; }
    
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public virtual EMPLEADO EMPLEADO1 { get; set; }
        public virtual ESTADOPEDIDO ESTADOPEDIDO1 { get; set; }
    }
}
