//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLEPEDIDO = new HashSet<DETALLEPEDIDO>();
        }
    
        public long IDPRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public long STOCK { get; set; }
        public long PRECIO { get; set; }
        public long ADMINISTRADOR { get; set; }
        public long TIPOPRODUCTO { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR1 { get; set; }
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public virtual TIPOPRODUCTO TIPOPRODUCTO1 { get; set; }
    }
}
