//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public DbSet<AUTH_GROUP> AUTH_GROUP { get; set; }
        public DbSet<AUTH_GROUP_PERMISSIONS> AUTH_GROUP_PERMISSIONS { get; set; }
        public DbSet<AUTH_PERMISSION> AUTH_PERMISSION { get; set; }
        public DbSet<AUTH_USER> AUTH_USER { get; set; }
        public DbSet<AUTH_USER_GROUPS> AUTH_USER_GROUPS { get; set; }
        public DbSet<AUTH_USER_USER_PERMISSIONS> AUTH_USER_USER_PERMISSIONS { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DETALLEFACTURA> DETALLEFACTURA { get; set; }
        public DbSet<DETALLEPEDIDO> DETALLEPEDIDO { get; set; }
        public DbSet<DJANGO_ADMIN_LOG> DJANGO_ADMIN_LOG { get; set; }
        public DbSet<DJANGO_CONTENT_TYPE> DJANGO_CONTENT_TYPE { get; set; }
        public DbSet<DJANGO_MIGRATIONS> DJANGO_MIGRATIONS { get; set; }
        public DbSet<DJANGO_SESSION> DJANGO_SESSION { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<ESTADOFACTURA> ESTADOFACTURA { get; set; }
        public DbSet<ESTADOHABITACION> ESTADOHABITACION { get; set; }
        public DbSet<ESTADOPEDIDO> ESTADOPEDIDO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<HABITACION> HABITACION { get; set; }
        public DbSet<HUESPED> HUESPED { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECEPCIONPRODUCTO> RECEPCIONPRODUCTO { get; set; }
        public DbSet<SERVICIOCOMEDOR> SERVICIOCOMEDOR { get; set; }
        public DbSet<TIPOPRODUCTO> TIPOPRODUCTO { get; set; }
        public DbSet<TIPOSERVICIO> TIPOSERVICIO { get; set; }
        public DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
